git add .github/workflows/deploy.yml
git commit -m "Fix Quartz deploy workflow (Node 22 + npm update)"
git push origin principalnamename: Deploy Quartz site

on:
  push:
    branches: ["principal"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies (force compatible npm)
        run: |
          npm install -g npm@latest
          npm ci

      - name: Build Quartz
        run: npx quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
